spring:
  application:
    name: apigateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://authservice:8083
          predicates:
            - Path=/api/auth/**

        - id: joke-service
          uri: http://jokeservice:8081
          predicates:
            - Path=/api/jokes/**

        - id: quote-service
          uri: http://quoteservice:8082
          predicates:
            - Path=/api/quotes/**

server:
  port: 8080
